### ISSUE TITLE
FIND: Parameter format not correct

### ISSUE THREAD

**Issue by woubuc** [codecov/codecov-node#39] opened 2016-12-01 21:30 UTC
I'm trying to get Codecov working for my application, but every time I try to run it I get as far as `==> Scanning for reports` and then it throws the following error:

```
FIND: Parameter format not correct
child_process.js:526
    throw err;
    ^

Error: Command failed: find F:\app -type f \( -name '*coverage.*' -or -name 'nosetests.xml' -or -name 'jacoco*.xml' -or -name 'clover.xml' -or -name 'report.xml' -or -name 'cobertura.xml' -or -name 'luacov.report.out' -or -name 'lcov.info' -or -name '*.lcov' -or -name 'gcov.info' -or -name '*.gcov' -or -name '*.lst' \) -not -name '*.sh' -not -name '*.data' -not -name '*.py' -not -name '*.class' -not -name '*.xcconfig' -not -name 'Coverage.profdata' -not -name 'phpunit-code-coverage.xml' -not -name 'coverage.serialized' -not -name '*.pyc' -not -name '*.cfg' -not -name '*.egg' -not -name '*.whl' -not -name '*.html' -not -name '*.js' -not -name '*.cpp' -not -name 'coverage.jade' -not -name 'include.lst' -not -name 'inputFiles.lst' -not -name 'createdFiles.lst' -not -name 'coverage.html' -not -name 'scoverage.measurements.*' -not -name 'test_*_coverage.txt' -not -path '*/vendor/*' -not -path '*/htmlcov/*' -not -path '*/home/cainus/*' -not -path '*/virtualenv/*' -not -path '*/js/generated/coverage/*' -not -path '*/.virtualenv/*' -not -path '*/virtualenvs/*' -not -path '*/.virtualenvs/*' -not -path '*/.env/*' -not -path '*/.envs/*' -not -path '*/env/*' -not -path '*/envs/*' -not -path '*/.venv/*' -not -path '*/.venvs/*' -not -path '*/venv/*' -not -path '*/venvs/*' -not -path '*/.git/*' -not -path '*/.hg/*' -not -path '*/.tox/*' -not -path '*/__pycache__/*' -not -path '*/.egg-info*' -not -path '*/$bower_components/*' -not -path '*/node_modules/*' -not -path '*/conftest_*.c.gcov'
FIND: Parameter format not correct

    at checkExecSyncError (child_process.js:483:13)
    at execSync (child_process.js:523:13)
    at Object.upload (F:\app\node_modules\codecov\lib\codecov.js:260:18)
    at Object.<anonymous> (F:\app\node_modules\codecov\bin\codecov:24:9)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
```

I'm using the latest (afaik) v1.0.1 installed from npm just now.

**Comment by mlewand** [comment] 2017-02-26 00:24
Same thing happen to me when I tried to generate coverage reports from AppVeyor.

Looking at stack trace, it's caused by this line: https://github.com/codecov/codecov-node/blob/f0c8aeb345f899e25d21682367e4413497bd558e/lib/codecov.js#L230

Most likely some Unix-specific call.

**Comment by eddiemoore** [comment] 2017-03-14 23:28
Duplicate of #2

**Closed by eddiemoore** 2017-03-14 23:28 UTC
