### ISSUE TITLE
[CE-919] AWS CodeBuild detected, but fail to upload

### ISSUE THREAD

**Issue by blakemorgan** [codecov/codecov-node#152] opened 2019-10-07 15:16 UTC
When I run `npm test && codecov` (after the codecov package has been installed globally), I get the following output:

```
  _____          _   
 / ____|        | |   
| |     ___   __| | ___  ___ _____   __   
| |    / _ \ / _` |/ _ \/ __/ _ \ \ / /   
| |___| (_) | (_| |  __/ (_| (_) \ V /   
 \_____\___/ \__,_|\___|\___\___/ \_/   
                                v3.6.1 
==> Detecting CI Provider 
    AWS CodeBuild Detected 
==> Configuration:  
    Endpoint: https://codecov.io 
{ commit: 'c6df5d3b21ab1f6dc345b5e8a382b9895fc42ba8', 
  branch: 'dev', 
  package: 'node-v3.6.1' } 
==> Building file structure 
==> Generating gcov reports (skip via --disable=gcov) 
    $ find /codebuild/output/src294305816/src/github.com/byu-oit/campus-map -type f -name '*.gcno'  -exec gcov  {} + 
==> Scanning for reports 
    + /codebuild/output/src294305816/src/github.com/byu-oit/campus-map/coverage/lcov.info 
    + /codebuild/output/src294305816/src/github.com/byu-oit/campus-map/coverage/clover.xml 
==> Uploading reports 
    HTTP 400 
service must be ci-provider 
```

As you can see, Codecov detects AWS CodeBuild, but for some reason, when it tries to upload the report, a 400 error is returned with the message `service must be a ci-provider`.

**Comment by eddiemoore** [comment] 2019-10-07 23:59
Hi @blakemorgan , Can you submit a ticket to support@codecov.io

**Comment by trivikr** [comment] 2019-10-21 20:34
Any update on this?
We're also blocked because of this issue in https://github.com/aws/aws-sdk-js-v3/issues/392

**Comment by trivikr** [comment] 2019-10-23 17:41
The code which prints `"Uploading reports"`:
https://github.com/codecov/codecov-node/blob/d81c4f446b247a5517bae59c2d18bd2b46b780c4/lib/codecov.js#L520

The code which prints success/error:
https://github.com/codecov/codecov-node/blob/d81c4f446b247a5517bae59c2d18bd2b46b780c4/lib/codecov.js#L161-L172

The error shown in CodeBuild (from https://github.com/aws/aws-sdk-js-v3/pull/366):
```console
[Container] 2019/10/21 20:23:41 Phase complete: BUILD State: SUCCEEDED
[Container] 2019/10/21 20:23:41 Phase context status code:  Message: 
[Container] 2019/10/21 20:23:41 Entering phase POST_BUILD
[Container] 2019/10/21 20:23:41 Running command ./node_modules/.bin/codecov -f coverage/*.json
  _____          _  
 / ____|        | |  
| |     ___   __| | ___  ___ _____   __  
| |    / _ \ / _` |/ _ \/ __/ _ \ \ / /  
| |___| (_) | (_| |  __/ (_| (_) \ V /  
 \_____\___/ \__,_|\___|\___\___/ \_/  
                                v3.6.1
==> Detecting CI Provider
    AWS CodeBuild Detected
==> Configuration: 
    Endpoint: https://codecov.io
{ commit: '6594db294267328124117dc0aac6da3a7266e263',
  branch: 'dependabot/npm_and_yarn/commitlint/config-conventional-8.2.0',
  package: 'node-v3.6.1' }
==> Building file structure
==> Generating gcov reports (skip via --disable=gcov)
    $ find /codebuild/output/src367505339/src/github.com/aws/aws-sdk-js-v3 -type f -name '*.gcno'  -exec gcov  {} +
==> Targeting specific file
    + /codebuild/output/src367505339/src/github.com/aws/aws-sdk-js-v3/coverage/coverage-final.json
==> Uploading reports
    HTTP 400
service must be ci-provider
```

The success message shown with TravisCI (from https://github.com/aws/aws-sdk-js-v3/pull/416):
```console
$ ./node_modules/.bin/codecov -f coverage/*.json
  _____          _  
 / ____|        | |  
| |     ___   __| | ___  ___ _____   __  
| |    / _ \ / _` |/ _ \/ __/ _ \ \ / /  
| |___| (_) | (_| |  __/ (_| (_) \ V /  
 \_____\___/ \__,_|\___|\___\___/ \_/  
                                v3.5.0
==> Detecting CI Provider
    Travis CI Detected
==> Configuration: 
    Endpoint: https://codecov.io
{ commit: '1034e7ec74611df36c53facb367e1d8cab279324',
  branch: 'AllanFly120-patch-4',
  package: 'node-v3.5.0' }
==> Building file structure
==> Generating gcov reports (skip via --disable=gcov)
    $ find /home/travis/build/aws/aws-sdk-js-v3 -type f -name '*.gcno'  -exec gcov  {} +
==> Targeting specific file
    + /home/travis/build/aws/aws-sdk-js-v3/coverage/coverage-final.json
==> Uploading reports
    Success!
    View report at: https://codecov.io/github/aws/aws-sdk-js-v3/commit/1034e7ec74611df36c53facb367e1d8cab279324
Done. Your build exited with 0.
```

**Comment by trivikr** [comment] 2019-10-23 18:00
This issue could be related to naming of service?
* Semaphore CI also faced the same issue as discussed in https://github.com/codecov/codecov-node/pull/145#issuecomment-533516853
* It was fixed in https://github.com/codecov/codecov-node/pull/146

**Comment by trivikr** [comment] 2019-10-23 18:03
Checked the naming of CodeBuild:
* It's `"codebuild"` in `lib/services/codebuild.js`
https://github.com/codecov/codecov-node/blob/9bde0721eb3a5549ad8ae21e2b18d92dbca301b5/lib/services/codebuild.js#L9
* Search results for other occurrences of `"codebuild"` in this repository https://github.com/codecov/codecov-node/search?q=codebuild&type=Code

**Comment by trivikr** [comment] 2019-10-23 18:05
As per comment https://github.com/codecov/codecov-bash/issues/99#issuecomment-349644953, the issue is likely to be on the server side

**Comment by eddiemoore** [comment] 2019-10-24 22:27
Yeah it's a server side thing. I'm only a contributor and don't actually work at Codecov. However I will ask the team if they can do something about it.

**Comment by trivikr** [comment] 2019-10-25 14:37
Thank you @eddiemoore for the response.
I've created support ticket with CodeCov at https://codecov.freshdesk.com/support/tickets/2303

**Comment by drazisil** [comment] 2019-10-25 14:39
Thanks for raising this, @trivikr 

Yes, adding any new CI provider service to an uploader requires that service name to be added to the upload endpoint to ensure Codecov can handle it correctly. It looks like that was missed here as we didn't know about this change.

I've raised a PR on the backend, hope to have it merged and deployed soon.

**Comment by trivikr** [comment] 2019-10-25 14:43
Thank you @drazisil for raising PR in the backend.
Is there a place where I can follow up the merge and deployment updates?

**Comment by trivikr** [comment] 2019-10-25 19:48
Issue created with codecov-bash at https://github.com/codecov/codecov-bash/issues/216

**Comment by drazisil** [comment] 2019-11-06 18:06
There is not, but I will update and close once deployed.

**Comment by drazisil** [comment] 2019-11-18 13:51
Thank you for your patience. I was on vacation last week, but i confirmed today that this has been deployed.

**Closed by drazisil** 2019-11-18 13:51 UTC

**Comment by slact** [comment] 2019-12-02 20:28
This appers to have broken uploading from Cirrus-CI. Previously, the output was
```
bash <(curl -s https://codecov.io/bash)
  _____          _
 / ____|        | |
| |     ___   __| | ___  ___ _____   __
| |    / _ \ / _` |/ _ \/ __/ _ \ \ / /
| |___| (_) | (_| |  __/ (_| (_) \ V /
 \_____\___/ \__,_|\___|\___\___/ \_/
                              Bash-8a28df4
x> No CI provider detected.
    Testing inside Docker? http://docs.codecov.io/docs/testing-with-docker
    Testing with Tox? https://docs.codecov.io/docs/python#section-testing-with-tox
    project root: .
--> token set from env
    Yaml found at: .codecov.yml
[...]
==> Uploading reports
    url: https://codecov.io
    query: branch=master&commit=[...]&build=&build_url=&name=&tag=&slug=[...]&service=&flags=&pr=&job=
    -> Pinging Codecov
https://codecov.io/upload/v4?package=bash-8a28df4&token=secret&branch=master&commit=[...]&build=&build_url=&name=&tag=&slug=[...]&service=&flags=&pr=&job=
    -> Uploading
    -> View reports at https://codecov.io/[...]
```

That is, even though the CI provider was not detected, the upload completed successfully.

Now, this happens instead:
```
bash <(curl -s https://codecov.io/bash)
  _____          _
 / ____|        | |
| |     ___   __| | ___  ___ _____   __
| |    / _ \ / _` |/ _ \/ __/ _ \ \ / /
| |___| (_) | (_| |  __/ (_| (_) \ V /
 \_____\___/ \__,_|\___|\___\___/ \_/
                              Bash-20191120-4983e44
==> Cirrus CI detected.
    project root: .
--> token set from env
    Yaml found at: .codecov.yml
[...]
==> Uploading reports
    url: https://codecov.io
    query: branch=master&commit=[...]&build=[...]&build_url=&name=&tag=&slug=[...]&service=cirrus&flags=&pr=&job=linux
    -> Pinging Codecov
https://codecov.io/upload/v4?package=bash-20191120-4983e44&token=secret&branch=master&commit=[...]&build=[...]&build_url=&name=&tag=&slug=[...]&service=cirrus&flags=&pr=&job=linux
    -> Uploading
    X> Failed to upload
    -> Sleeping for 30s and trying again...
    -> Pinging Codecov
https://codecov.io/upload/v4?package=bash-20191120-4983e44&token=secret&branch=master&commit=[...]&build=[...]&build_url=&name=&tag=&slug=[...]&service=cirrus&flags=&pr=&job=linux
    -> Uploading
    X> Failed to upload
    -> Sleeping for 30s and trying again...
    -> Pinging Codecov
https://codecov.io/upload/v4?package=bash-20191120-4983e44&token=secret&branch=master&commit=[...]&build=[...]&build_url=&name=&tag=&slug=[...]&service=cirrus&flags=&pr=&job=linux
    -> Uploading
    X> Failed to upload
    -> Sleeping for 30s and trying again...
    -> Pinging Codecov
https://codecov.io/upload/v4?package=bash-20191120-4983e44&token=secret&branch=master&commit=[...]&build=[...]&build_url=&name=&tag=&slug=[...]&service=cirrus&flags=&pr=&job=linux
    -> Uploading
    X> Failed to upload
    -> Sleeping for 30s and trying again...
    -> Uploading to Codecov
    HTTP 400
service must be ci-provider
```
